name: Add PR labels

on:
  workflow_call:
    inputs:
      CONF_PATH:
        description: Path to the labeler configuration file
        required: true
        type: string

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    name: Add labels on PR
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v5

    - name: Add pull request label
      uses: actions/labeler@v5
      with:
        configuration-path: ${{ inputs.CONF_PATH }}
