name: Add PR labels

on:
  workflow_call:
    inputs:
      CONF_PATH:
        description: Path to the labeler configuration file
        required: true
        type: string

jobs:
  label:
    name: Add labels on PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - name: Checks-out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Add pull request label
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        configuration-path: ${{ inputs.CONF_PATH }}
